spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/account_service_database
    username: wailrack
    password: 4270
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /accounts
  port: 8081